### ISSUE TITLE
language detection API is paid now

### ISSUE THREAD

**Issue by ipadabed** [mlava/translate#1]
can we have an option to have a fixed source language in extension settings to avoid the detection of API calls and keep the API subscription free of charge?

**Comment by mlava** [comment]
Yes, that's a good idea.
Let me work on that.
Cheers

**Comment by ipadabed** [comment]
When I try to test API on the RapidAPI website, I see this 401 error for "detect" call:
"401
▶{} 1 key

     *   message:"This endpoint is disabled for your subscription"

"
And it works well with "Translate" method call.
________________________________

**Comment by mlava** [comment]
Yep, sorry, I think you responded to an earlier version of my comment, which I edited.
Will work on a fix 🙂

**Comment by mlava** [comment]
Thanks for bringing this to my attention. @ipadabed 

Fixed in https://github.com/Roam-Research/roam-depot/pull/852 You just have to wait for it to be accepted by the Roam team.

**Comment by mlava** [comment]
This PR has been approved and the new version is available. Cheers!
